### ISSUE TITLE
Which language ‘tis?

### ISSUE THREAD

**Issue by menewol** [kinnounko/javascript-reverse-shell#1]
‘‘Tis JavaScript or Java?

**Comment by kinnounko** [comment]
This is javascript. It's in the title of the repo.

**Comment by menewol** [comment]
You mind explaining how this should work? Have never seen the usage of uncompiled Java-Code in javascript.

**Comment by kinnounko** [comment]
yeah, sorry. i have no clue where i got this from and why i put it on my github. will be deleting.
